name: soil-moisture-model
channels:
  - conda-forge
dependencies:
  - pytest
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - geopandas
  - matplotlib
  - cartopy
  - cmocean
  - shapely
  - xesmf >= 0.5.2
  - cf_xarray # separately, to ensure latest version
